#!/bin/bash

for i in $(ls *.pdb)
do
	name=${i:0:${#i}-4}
	echo $name
	./ff $name.pdb | gawk '{print $6" "$7" "$5}' > $name.opls
	cat  $name.pdb | grep ATOM | gawk '{print $6" "$7" "$8}' > $name.coors
done

