#!/bin/bash

if [ $# -lt 2 ]; then

   echo usage:  unpack_xyz multisystem.xyz output_prefix
   echo converts multisystem.xyz with many xyz coordinates to the list of files, which start with output_prefix 
   exit
fi

big=$1
prefix=$2

cp $big tmp

rec=1
lin=1

while [ 1 == 1 ];
do

  NN=$(cat tmp | wc -l)
  [ $NN == 0 ] && break; 

  nlin=$(head -n1 tmp)
  
  if [ $((nlin-1)) == -1 ]; then
     echo ERROR at record $rec line $lin
     exit
  fi

  echo $prefix$rec.xyz

  cat tmp | head -n$((nlin+2)) > $prefix$rec.xyz
  mv tmp tmp1
  cat tmp1 | tail -n+$((nlin+3)) > tmp

  rec=$((rec+1))
  lin=$((lin+nlin+2))
done





